In [1]:
import numpy as np

# 2.Numpy

행렬이나 일반적으로 대규모 다차원 배열을 쉽게 처리할 수 있도록 지원하는 파이썬의 라이브러리

references: 
- [numpy](https://numpy.org/doc/stable/reference/index.html#reference)
- [cs231 numpy](https://cs231n.github.io/python-numpy-tutorial/)
- [Python For Data Science Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

<br>

numpy 특징 <br>
- 파이썬 리스트에 비해 빠르고, 메모리 효율적
- 반복문 없이 배열에 대한 처리 지원
- 다양한 기능 제공
<br>
<br>

numpy 기능 <br>
- 1. shape: numpy dimension
- 2. ndim: shape에서 얼마나 나오는지
- 3. dtype: numpy 원소의 데이터 타입

## 2.1 배열 생성

파이썬 배열 -> numpy array

In [3]:
a = list(range(10))
a
np.array(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

직접 생성

In [4]:
np.array([1,2,3])
np.array([1,2,3], dtype=float)
np.array([1,2,3], dtype=str)
#데이터타입 혼용해서 사용할 수 없음

array([1, 2, 3])

In [13]:
b = np.array(a)+1

In [6]:
np.array([[1,2,3],[4,5,6]], dtype=float).shape

(2, 3)

### 2.1.1 기본 배열 생성

#### arange
일정 범위의 배열을 생성 <br>
python의 range와 유사 <br>
단, arange는 실수 사용 가능 <br>

> 주의 <br>
np.arange(-3, 3, 0.5, dtype=int) <br>
array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

<br>

사용법
```python
x = np.arange(0, 10)
x = np.arange(-5, 5, 0.5)
```

In [16]:
np.arange(-5, 5,0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [18]:
#결과가 왜곡되지 않도록 주의!
np.arange(-5,5,0.5, dtype=int)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14])

In [15]:
list(np.arange(1.2, 10.5))

[1.2,
 2.2,
 3.2,
 4.200000000000001,
 5.200000000000001,
 6.200000000000001,
 7.200000000000002,
 8.200000000000001,
 9.200000000000001,
 10.200000000000001]

#### linspace

arange와 유사 <br>
start와 stop를 주어진 숫자 만큼 분할

<br>

사용법
```python
x = np.linspace(2, 3, num=5)
x = np.linspace(2, 3, num=5, endpoint=False)    # 끝 점 미포함 
```

In [22]:
np.linspace(1,5,num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [21]:
np.linspace(1,5,num=10,endpoint=False) #끝 점 미포함

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6])

#### eye

대각행렬이 1이고 나머지가 0인 행렬 생성 <br>
k를 이용하여 1의 위치를 조정할 수 있음 <br>
<br>

사용법
```python
x = np.eye(10)    # np.identity와 동일
x = np.eye(10, k =1)
```

In [30]:
np.eye(5)
np.eye(5,k=1)
np.eye(5,k=-1)
np.eye(5,k=1) + np.eye(5,k=-1)

array([[0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0.]])

#### zeros

shape을 입력하면 모든 값이 0인 해당 shape에 맞는 배열 생성 <br>

사용법
```python
x = np.zeros(5)
x = np.zeros((5, 2), dtype=float)
```

In [33]:
np.zeros(5)
np.zeros((5,2))
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

#### ones

shape을 입력하면 모든 값이 1인 해당 shape에 맞는 배열 생성 <br>
<br>

사용법
```python
x = np.ones(5)
x = np.ones((5, 2), dtype=float)
```

In [37]:
np.ones(5)
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

#### full

shape과 숫자를 입력하면 입력한 숫자로 찬 해당 shape에 맞는 배열 생성 <br>
<br>

사용법
```python
x = np.full(5, np.inf)
x = np.full((5, 2), np.nan)
```

In [39]:
np.full((5,2),10)
np.full((5,2),np.nan) #inf 무한대 / nan 유효하지 않은 값

array([[nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan]])

#### tril

lower triangle matrix 생성 <br>
m값을 이용하여 삼각행렬 이동 가능 <br>
<br>

사용법
```python
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
```

In [40]:
np.tril([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [41]:
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

array([[ 1,  0,  0],
       [ 4,  5,  0],
       [ 7,  8,  9],
       [10, 11, 12]])

#### triu

upper triangle matrix 생성 <br>
m값을 이용하여 삼각행렬 이동 가능 <br>
<br>

사용법
```python
x = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)
```

In [42]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9],
       [0, 0, 0]])

In [43]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

### 2.1.2 랜덤 배열 생성

#### random

균등분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.random(size=(2, 3))    # size: dim
```

In [55]:
np.random.seed(0) #random값 고정

In [56]:
np.random.random(size=(2, 3))  #값 0<=x<1 

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

#### randint

지정한 범위 내에서 임의의 수 생성

사용법
```python
x = np.random.randint(0, 10, size=(5,2))    # size: dim
```

In [59]:
np.random.randint(0, 10, size=(5,2))

array([[1, 5],
       [9, 8],
       [9, 4],
       [3, 0],
       [3, 5]])

#### normal

정규분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.normal(loc=0, scale=1, size=(2, 3))
# loc: 평균
# scale: 분산
# size: dim
```

In [61]:
np.random.normal(loc=10, scale=20, size=(3, 5))

array([[-41.05979632,  23.07237191,  27.28872398,  -4.84330041,
         55.39509248],
       [-19.08731349,  10.91517035,   6.256323  ,  40.65558429,
         39.3871754 ],
       [ 13.09894851,  17.56325039,  -7.75571495, -29.61592936,
          3.04175701]])

#### randn

표준정규분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.randn(2, 3)
```

In [63]:
np.random.randn(2, 3)
#loc=0, scale=1

array([[-1.42001794, -1.70627019,  1.9507754 ],
       [-0.50965218, -0.4380743 , -1.25279536]])

## 2.2 배열 조작

In [66]:
a = np.random.randint(0,10,size=(2,5))
a

array([[3, 3, 2, 3, 4],
       [1, 2, 9, 1, 4]])

In [72]:
a[1,2]
a[1,2:5]
a[:,1] #1열값 가져오기


array([[ 3,  3,  2, 10,  4],
       [ 1,  2,  9,  1,  4]])

In [74]:
a[0,3]=10
a[1,3:]=20
a[:,2]=30
a

array([[ 3,  3, 30, 10,  4],
       [ 1,  2, 30, 20, 20]])

### 2.2.1 배열 결합

#### concatenate

두 배열을 결합 <br>
<br>

사용법 
```python
a = np.arange(12).reshape(2, 6)
b = np.arange(12).reshape(2, 6)
np.concatenate([a, b], axis=0)
np.concatenate([a, b], axis=1)
```

In [2]:
a = np.arange(12).reshape(2, 6)
b = np.arange(12).reshape(2, 6)
np.concatenate([a, b], axis=0)
np.concatenate([a, b], axis=1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [3]:
a = np.arange(24).reshape(2, 3, 4)
b = np.arange(24).reshape(2, 3, 4)
np.concatenate([a, b], axis=0)
np.concatenate([a, b], axis=1)
np.concatenate([a, b], axis=2)

#(2,3,4) (3,3,4)는 axis=0만 concatenate가능

array([[[ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 12, 13, 14, 15],
        [16, 17, 18, 19, 16, 17, 18, 19],
        [20, 21, 22, 23, 20, 21, 22, 23]]])

In [4]:
a = np.array([1,2,3])
np.concatenate([a,[4]])

array([1, 2, 3, 4])

### 2.2.2 배열 분할

#### array_split

주어진 배열을 분할 <br>
<br>

사용법
```python
x = np.arange(9.0)
np.split(x, 3)
np.array_split(x, [3, 5, 6, 10])
```

In [12]:
x = np.arange(10)
np.array_split(x, 3)


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [13]:
x = np.arange(11)
assert len(x)%3 == 0 #조건이 참이면 실행 거짓이면 에러
np.array_split(x, 3)

AssertionError: 

In [16]:
np.array_split(x, [2, 3, 4]) #2미만/ 3미만/4미만
# np.array_split(x, [3, 2, 4])

[array([0, 1]), array([2]), array([3]), array([ 4,  5,  6,  7,  8,  9, 10])]

### 2.2.3 차원 변경

#### reshape

배열의 모양을 원하는 형태로 바꿈 <br>
단, 바꾸는 배열의 차원 곱은 원 배열의 차원 곱과 일치해야 함 <br>
<br>

사용법
```python
x = np.arange(30)
x.reshape(5, 6)
```


In [21]:
x = np.arange(30)
x.reshape(5, 6)
x.reshape(1, 5, 6, 1) #차원 확장 가능


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

#### flatten

배열을 1차원 배열로 바꿈 <br>
<br>
사용법 <br>
```python
x = np.arange(30).reshape(2, 5, 3)
x.flatten()
```

In [23]:
x = np.arange(30).reshape(2, 5, 3)
x
x.flatten() #1차원으로 바꿔줌

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### squeeze

불필요한 차원을 제거 <br>
즉, 길이가 0인 차원을 제거 <br>
<br>

사용법
```python
x = np.arange(10).reshape(10, 1, 1)
x.squeeze()
```

In [26]:
x = np.arange(3).reshape(3, 1)
x.squeeze()

array([0, 1, 2])

#### expand_dims

차원 추가 <br>
<br>

사용법
```python
x = np.arange(10)
np.expand_dims(x, 0)
```

In [31]:
x = np.arange(10)
np.expand_dims(x, 0) #0(1차원)과 1(2차원)만 가능

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### 2.2.4 모양 변경

##### roll

배열을 입력한 수 만큼 이동 <br>
<br>

사용법
```python
x = np.arange(10)
np.roll(x, 2)
```

```python
x = np.reshape(x, (2, 5))
np.roll(x, 1)
np.roll(x, -1, axis=0)
np.roll(x, -1, axis=1)
```

In [35]:
x = np.arange(10)
np.roll(x, 1) #오른쪽으로 1칸 밀었음
np.roll(x, -1) #왼쪽으로 1칸 밀었음

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [43]:
x = np.arange(10).reshape(2,5)
print(np.roll(x,1))
print(np.roll(x,3, axis=0))
print(np.roll(x,1, axis=1))

[[9 0 1 2 3]
 [4 5 6 7 8]]
[[5 6 7 8 9]
 [0 1 2 3 4]]
[[4 0 1 2 3]
 [9 5 6 7 8]]


##### flip

지정된 축을 기준으로 배열을 뒤집음 <br>
<br>

사용법

```python
x = np.arange(10).reshape(5, 2)
np.flip(x, 0)
```


In [44]:
x = np.arange(10).reshape(5, 2)
print(x)
print(np.flip(x, 0))
print(np.flip(x, 1))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[8 9]
 [6 7]
 [4 5]
 [2 3]
 [0 1]]
[[1 0]
 [3 2]
 [5 4]
 [7 6]
 [9 8]]


In [45]:
print(x[::-1,:])
print(x[:,::-1])

[[8 9]
 [6 7]
 [4 5]
 [2 3]
 [0 1]]
[[1 0]
 [3 2]
 [5 4]
 [7 6]
 [9 8]]


### 2.2.5 축 변경

#### swapaxes

두 축의 위치를 지정하여 변경 <br>
<br>

사용법
```python
x = np.arange(100).reshape(5, 2, 10)
x.swapaxes(0, 2)    # 0 <-> 2
```

In [49]:
x = np.arange(100).reshape(5, 2, 10)
x.swapaxes(0, 2).shape

(10, 2, 5)

In [55]:
x = np.arange(24).reshape(2,3,4)
print(x.reshape(4,3,2))
print(x.swapaxes(0,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


#### transpose

여러 축의 위치를 변경 <br>
transpose에 들어가는 인자는 축의 순서 <br>
<br>

사용법

```python
x = np.arange(100).reshape(5, 2, 10)
x.transpose(0, 2, 1)    # 1번 축과 2번 축을 바꿈
x.transpose(2, 0, 1)    # 2->0, 0->1, 1->2
```

In [57]:
x = np.arange(100).reshape(5, 2, 10)
x.transpose(2, 0, 1).shape #새롭게 바뀔 축번호 넣기

(10, 5, 2)

### 2.2.6 배열 정렬

#### sort

주어진 축을 기준으로 배열 정렬 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
x.sort(axis=1)
x
```



In [59]:
x = np.random.randint(0, 10, (5, 2))
x.sort(axis=0)
x

array([[1, 1],
       [1, 2],
       [4, 5],
       [6, 6],
       [6, 7]])

#### argsort

주어진 축을 기준으로 정렬된 배열의 인덱스 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
x.argsort(axis=1)
```


In [62]:
x = np.random.randint(0, 10, 10)
print(x)
print(x.argsort()) #인덱스번호

[4 1 5 2 6 2 4 7 0 1]
[8 1 9 3 5 0 6 2 4 7]


### 2.2.7 기타

##### unique

축을 기준으로 배열 내의 중복값 제거 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
np.unique(x, axis=0)
```

In [63]:
x = np.array([1,1,1,2,3,4])
np.unique(x)

array([1, 2, 3, 4])

#### nan_to_num

배열 내의 nan 값을 특정 숫자로 변환 <br>
<br>

사용법
```python
x = np.full((3, 4), np.nan)
np.nan_to_num(x, nan=1)


In [70]:
x = np.full((3,4),np.nan)
x
np.nan_to_num(x,nan=-1)

array([[-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.]])

#### trim_zeros

배열 내의 0값을 제거 <br>
<br>

사용법
```python
x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
np.trim_zeros(x, trim='f')    # 앞의 0만 제거
np.trim_zeros(x, trim='b')    # 뒤의 0만 제거
np.trim_zeros(x, trim='fb')   # 앞뒤 0 제거
```

In [72]:
x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
print(np.trim_zeros(x, trim='f'))    # 앞의 0만 제거
print(np.trim_zeros(x, trim='b'))    # 뒤의 0만 제거
print(np.trim_zeros(x, trim='fb'))   # 앞뒤 0 제거


[1 2 3 0 2 1 0]
[0 0 0 1 2 3 0 2 1]
[1 2 3 0 2 1]


stride_tricks

배열을 주어진 윈도우 만큼 분할 <br>
<br>

사용법
```python
x = np.arange(10)
y = np.lib.stride_tricks.sliding_window_view(x, 3)
```

In [76]:
x = np.arange(1,11)
np.lib.stride_tricks.sliding_window_view(x, 5) #숫자= 자르고 싶은 갯수

array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

## 2.3 배열 탐색

### argmax

축을 기준으로 배열에서 최댓값의 index 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.argmax(x)
np.argmax(x, axis=0)
```

In [83]:
x = np.arange(6).reshape(2,3)
x
np.argmax(x) #축 정보없으면 가장 큰 값 인덱스
np.argmax(x,axis = 0)

array([1, 1, 1], dtype=int64)

### argmin

축을 기준으로 배열에서 최솟값의 index 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.argmin(x)
np.argmin(x, axis=0)
```



In [90]:
x = np.arange(6).reshape(2,3)
np.argmin(x)
np.argmin(x, axis=0)

array([[0, 1, 2],
       [3, 4, 5]])

### where

특정 조건에 맞는 값의 index 반환 또는 값 변환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.where(x < 5)    # 조건을 만족하는 값의 인덱스 반환
np.where(x < 5, 1, 0)    # x가 5보다 작은 값은 1, 그렇지 않으면 0
```

In [92]:
x = np.random.randint(0,20, (5,4))
x

array([[13, 14, 13,  7],
       [12,  2,  3, 18],
       [18, 13,  6,  9],
       [12,  3, 14,  6],
       [16, 16,  8,  5]])

In [93]:
np.where(x < 10)

(array([0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int64),
 array([3, 1, 2, 2, 3, 1, 3, 2, 3], dtype=int64))

In [94]:
np.where(x<10, x, x-10) #(조건/True/False)

array([[3, 4, 3, 7],
       [2, 2, 3, 8],
       [8, 3, 6, 9],
       [2, 3, 4, 6],
       [6, 6, 8, 5]])

### extract

특정 조건에 맞는 값을 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.extract(x > 2, x)
```

In [97]:
x = np.random.randint(0,20, (5,4))
print(x)
np.extract(x < 10, x)

[[ 4 17 15 17]
 [19 16 10  0]
 [17  4 15  5]
 [18  6  4  9]
 [12 11 13  2]]


array([4, 0, 4, 5, 6, 4, 9, 2])

##  2.4 배열 연산

### matmul

행렬 곱 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
y = np.random.randint(0, 10, size=(2,2))

np.matmul(x, y)
x @ y
```

In [98]:
x = np.random.randint(0, 10, size=(2,2))
y = np.random.randint(0, 10, size=(2,2))
print(x);print(y)

[[6 7]
 [3 0]]
[[6 2]
 [6 8]]


In [100]:
np.matmul(x,y)
x @ y #행렬 곱하기

array([[78, 68],
       [18,  6]])

In [101]:
x*y #원소별 곱하기

array([[36, 14],
       [18,  0]])

### eigen

eigenvalue, eigenvector 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.eig(x)
```



In [107]:
x = np.random.randint(0, 10, size=(2,2))
x

array([[2, 8],
       [0, 9]])

In [108]:
np.linalg.eig(x)

(array([2., 9.]),
 array([[1.        , 0.75257669],
        [0.        , 0.65850461]]))

### det

배열의 행렬식을 구함 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.det(x)
```

In [109]:
np.linalg.det(x)

18.000000000000004

### trace
대각원소의 합 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.trace(x)
```

In [110]:
np.trace(x)

11

### solve

선형 방정식의 해를 반환 <br>
<br>


사용법
```python
#  x_0 + 2*x_1 = 1
# 3x_0 + 5*x_1 = 2:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
np.linalg.solve(a, b)
```

In [111]:
#  x_0 + 2*x_1 = 1
# 3x_0 + 5*x_1 = 2

a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
np.linalg.solve(a, b)

array([-1.,  1.])

### inv

역행렬 반환 <br>
<br>


사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.inv(x)
```

In [112]:
x

array([[2, 8],
       [0, 9]])

In [113]:
np.linalg.inv(x)

array([[ 0.5       , -0.44444444],
       [ 0.        ,  0.11111111]])

## 2.5 통계 함수

#### ptp

축별 최댓값 - 최솟값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.ptp(axis=0)
```

In [114]:
x = np.random.randint(0,10, size=(4,3))
x

array([[1, 5, 0],
       [0, 1, 7],
       [5, 5, 1],
       [6, 1, 9]])

In [115]:
x.ptp(axis=0) #최대값 최소값 차이값

array([6, 4, 9])

#### median

축별 중앙값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
np.median(x, axis=0)
```

In [116]:
np.median(x, axis=0)

array([3., 3., 4.])

### sum

축별 합 산출 <br>
<br>

사용법
```python
x = np.array([3, 4, 5])
x.sum(axis=1)
```

In [117]:
x.sum(axis=0)

array([12, 12, 17])

### average

축별 가중합 산출 <br>
<br>

사용법
```python
x = np.array([3, 4, 5])
np.average(x, weights=[0.5, 0.3, 0.2])
```

In [120]:
x = np.array([3, 4, 5])
np.average(x, weights=[1, 1, 2])

4.25

### mean

축별 평균 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.mean(axis=1)
```

In [121]:
x = np.random.randint(0,10, size=(4,3))
x

array([[3, 2, 4],
       [4, 9, 2],
       [1, 9, 9],
       [1, 9, 5]])

In [124]:
x.mean(axis=0)

array([2.25, 7.25, 5.  ])

### min

축별 최솟값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.min(axis=1)
```

In [123]:
x.min(axis=0)

array([1, 2, 2])

### max

축별 최댓값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.max(axis=1)
```

In [125]:
x.max(axis=0)

array([4, 9, 9])

### std
축별 표준편차 산출 <br>
<br>

사용법

```python
x = np.arange(12).reshape(4,3)
x.std(axis=1)
```

In [126]:
x.std(axis=0)

array([1.29903811, 3.03108891, 2.54950976])

### cov

공분산 산출 <br>
<br>

사용법
```python
x = np.random.rand(25).reshape(5, 5)
np.cov(x)
```

In [127]:
x = np.random.rand(25).reshape(5, 5)
x

array([[0.28598674, 0.67997749, 0.91860237, 0.36828471, 0.62745284],
       [0.19400759, 0.12272709, 0.23710108, 0.60336089, 0.62701142],
       [0.06217819, 0.61178045, 0.49380401, 0.44676279, 0.94912654],
       [0.69409352, 0.66166982, 0.40276786, 0.54142951, 0.46282006],
       [0.05486218, 0.76236142, 0.90682053, 0.73809005, 0.52488395]])

In [128]:
np.cov(x)

array([[ 0.0645221 , -0.01386171,  0.04265929, -0.02083154,  0.06188725],
       [-0.01386171,  0.05735645,  0.0385203 , -0.01441084,  0.00694118],
       [ 0.04265929,  0.0385203 ,  0.10198993, -0.02213845,  0.05349953],
       [-0.02083154, -0.01441084, -0.02213845,  0.01563788, -0.02504888],
       [ 0.06188725,  0.00694118,  0.05349953, -0.02504888,  0.11058822]])

In [129]:
np.array([[3,4,5],[6,7,8]]).T
#3X2 행렬을 2X3행렬로 바꿈

array([[3, 6],
       [4, 7],
       [5, 8]])

In [134]:
#예제
np.arange(1,101)
np.int32((np.arange(1,101)-1)/20) + 1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])